### PR TITLE
Stops autoClose of end tag if it already exists

### LINKED ISSUE #314: Dont autoclose tag if the closing tag already exists.
When I start with:

```xml
<a  </a>
```

then type '>'

the result is:

```xml
<a></a> </a>
```

Fix this so nothing happens in this case.

### PR DESCRIPTION
**Pull request by NikolasKomonen**
Fixes #314, #239

### CODE REVIEW

**Comment by fbricon** [comment]
Problem is it prevents completion of tags if they're nested:
```xml
<abc>
    <abc|  <!-- closing with > doesn't autoclose the tag -->
</abc>
```

You need to check if tags are balanced

**Comment by NikolasKomonen** [comment]
@fbricon I fixed the case you mentioned

**Comment by fbricon** [comment]
No it's not working. And a simple "<a>" is not autocompleted either

**Comment by fbricon** [comment]
Excellent! It brings tears of joy to my eyes ;-)

**Pull request merged**
