### PR TITLE
Add support for `textDocument/typeDefinition` from XML to XMLSchema/DTD

### LINKED ISSUE #371: Add support for `textDocument/typeDefinition` from XML to XMLSchema/DTD
When XML file is bound to an XML Schema or DTD it should be cool to manage type definition inside XML to open the XML Schema (element or attribute) / DTD element/attrlist which defines the XML element/attribute.

Take a sample with this xml:

```xml
<book isbn="0836217462" xmlns="http://example.org/ns/books/">
   <title>bla bla bla</title>
</book>
```

bound to this XML Schema:

```xml
<xsd:element name="book">
 <xsd:complexType>
  <xsd:sequence>
   <xsd:element name="title" type="xsd:string"/>
   <xsd:attribute name="isbn" type="xsd:string"/>
  </xsd:sequence>
 </xsd:complexType>
</xsd:element>

```

* when type definition is done in the xml attribute `book/@isbn` it should open the XML Schema and select the value of @name of `<xsd:attribute name="isbn" ` (isbn).

* when type definition is done in the xml element`book/title` it should open the XML Schema and select the value of @name of `<xsd:element name="title" ` (title).

Same thing should be done for XML bound to DTD

### PR DESCRIPTION
**Pull request by angelozerr**
Fix #371

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
You can play with this XSD Type Definition PR, but my code is very ugly. XSD Type definition works with `global `and `local` `xs:element` local and global. `xs:attribute` is not implemented yet. I will work on it after cleaning my code and writing tests.

Here a demo:

XSDTypeDefinitionDemo

**Comment by fbricon** [comment]
```
java.io.FileNotFoundException: /fbricon/.lsp4xml/cache/http/maven.apache.org/xsd/maven-4.0.0.xsd (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.google.common.io.Files$FileByteSource.openStream(Files.java:129)
	at com.google.common.io.Files$FileByteSource.read(Files.java:153)
	at com.google.common.io.ByteSource$AsCharSource.read(ByteSource.java:470)
	at org.eclipse.lsp4xml.extensions.xsd.contentmodel.CMXSDDocument.findTypeLocation(CMXSDDocument.java:239)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelTypeDefinitionParticipant.findTypeDefinition(ContentModelTypeDefinitionParticipant.java:30)
	at org.eclipse.lsp4xml.services.XMLTypeDefinition.findTypeDefinition(XMLTypeDefinition.java:52)
	at org.eclipse.lsp4xml.services.XMLLanguageService.findTypeDefinition(XMLLanguageService.java:220)
	at org.eclipse.lsp4xml.XMLTextDocumentService.lambda$typeDefinition$15(XMLTextDocumentService.java:321)
	at java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1105)
	at java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1070)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by fbricon** [comment]
cache location should be /Users/fbricon/.lsp4xml/cache/ instead of /fbricon/.lsp4xml/cache

**Comment by angelozerr** [comment]
@fbricon please retry this PR. I have written several tests and all are passing. My code should be clean now. Thank's for your review.

**Comment by angelozerr** [comment]
@fbricon I have rebase my PR and finish to write tests. You can review it when you will have time.

**Pull request merged**
