### PR TITLE
Documents with an Internal Subset DOCTYPE shouldn't stop trying to bind

### LINKED ISSUE #379: Documents with an Internal Subset DOCTYPE shouldn't stop trying to bind
My organization has documents like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
    <!ENTITY foo "Bar">
]>
```

I'm trying to bind these documents using `fileAssociations`, but lsp4xml stops trying to bind at the `DOCTYPE`. It should continue looking for `xsi:schemaLocation` and in `fileAssociations` when the `DOCTYPE` lacks a DTD reference.

### PR DESCRIPTION
**Pull request by angelozerr**
Fix #379

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
To check this PR, create XML file like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article [
  <!ENTITY nbsp "entity-value">

]>           
<article>
	&nbsp;
</article>
```

It should not have error (this is the fix of the PR)

Declare an <!ELEMENT like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article [
  <!ENTITY nbsp "entity-value">
  <!ELEMENT element-name (#PCDATA)>
]>           
<article>
	&nbsp;
</article>
```

It should have error.

Change element-name to article to fix error:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article [
  <!ENTITY nbsp "entity-value">
  <!ELEMENT article (#PCDATA)>
]>           
<article>
	&nbsp;
</article>
```

**Comment by fbricon** [comment]
It works but the validation error range is off
Screen Shot 2019-07-18 at 10 47 28 AM

**Comment by angelozerr** [comment]
Indeed I discovered this problem yesterday, I created an issue yesterday https://github.com/angelozerr/lsp4xml/issues/518 and @xorye should work on it.

**Comment by angelozerr** [comment]
@fbricon I merged this PR since test passed and your test is OK. I need this PR to rebase my work with XSD 1.1. For error range please see https://github.com/angelozerr/lsp4xml/issues/518

**Pull request merged**
