### PR TITLE
Discrepancy in completion between prefixed and default namespaces

### LINKED ISSUE #311: Discrepancy in completion between prefixed and default namespaces
https://github.com/redhat-developer/vscode-xml/issues/87

### PR DESCRIPTION
**Pull request by angelozerr**
Fix #311

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
To review this PR, 

 * download the attached project in https://github.com/redhat-developer/vscode-xml/issues/87#issue-380298676 (vscode-xml-catalog-test.zip)

 * open mini-catalog.xml set cursor after comment 

`  
`

open the completion, edmx:DataServices and edmx:Reference, #region, #endregion should only displayed (not edm:Annotation)

**Comment by xorye** [comment]
> * open mini-catalog.xml set cursor after comment
@angelozerr Did you mean mini-catalog-prefix.xml instead? Because the original issue [here](https://github.com/redhat-developer/vscode-xml/issues/87) said that mini-catalog.xml  was good

**Comment by angelozerr** [comment]
> Did you mean mini-catalog-prefix.xml instead? Because the original issue here said that mini-catalog.xml was good

Ooops sorry, yes it was that, but the 2 XML file mini-catalog-prefix.xml  and mini-catalog.xml should do the same completion result.

**Comment by xorye** [comment]
@angelozerr  Works great! The completion also matches up  with the comments in `/examples/mini-catalog-prefix`, not just for `<!-- should suggest edmx:DataServices and edmx:Reference here -->`.

**Comment by angelozerr** [comment]
Thanks @xorye for your feedback!

**Pull request merged**
