### PR TITLE
Fix completion duplicate with xs:any

### PR DESCRIPTION
**Pull request by angelozerr**
See #177

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by fbricon** [comment]
On completion, all tags already in the document are missing the documentation part which points to their source (tns.xsd). All other tags have it

**Comment by fbricon** [comment]
well actually no, this is not the proper cause, eg. DockLayout has no `source tns.xsd` and it's not already defined in the test-page.xml either

**Comment by fbricon** [comment]
Seems to be concerning all *Layout tags. Probably a different bug then

**Comment by angelozerr** [comment]
> Seems to be concerning all *Layout tags. Probably a different bug then

I think it's because I provide local and global elements both. In DockLayout case, local element is added beforethe global element and it seems I cannot get the source in this case. To fix the problem completion provides only global elements.

**Comment by fbricon** [comment]
so just add local elements after global ones?

**Comment by angelozerr** [comment]
> so just add local elements after global ones?

I collect now local and global elements and fix bug with source. I have written test for that.

**Pull request merged**
