### PR TITLE
Add support for `textDocument/definition` for DTD

### LINKED ISSUE #233: Add support for `textDocument/definition` for DTD
Support for hyperlink between DTD elements.

```
<!ELEMENT TVSCHEDULE (CHANNEL <-- Ctrl+Click go at <!ELEMENT CHANNEL
<!ELEMENT CHANNEL (BANNER,DAY+)>
```

### PR DESCRIPTION
**Pull request by angelozerr**
Fixes #233

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
To play with this PR, open the DTD https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/test/resources/dtd/svg.dtd

and do like the following demo:

DTDDefinitionWithSVG

It shoud work too when DOCTYPE inside XML is defined.

With this XML file:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE note [
	<!ELEMENT note (to,from,heading,body)>
	<!ELEMENT to (#PCDATA)>
	<!ELEMENT from (#PCDATA)>
	<!ELEMENT heading (#PCDATA)>
	<!ELEMENT body (#PCDATA)>
]>
<note>
	<to>Tove</to>
	<from>Jani</from>
	<heading>Reminder</heading>
	<body>Don't forget me this weekend!</body>
</note>
```

Ctrl+Click on the first `heading` (declared in 	`<!ELEMENT note (to,from,heading,body)>`) should set the cursor to the `declared heading` (	`<!ELEMENT heading (#PCDATA)>`)

**Comment by angelozerr** [comment]
@fbricon I have finished to clean my code and write several tests.

**Comment by NikolasKomonen** [comment]
@angelozerr 

I think this should be one hyperlink, not sure if this is not easily doable.

savag

**Comment by angelozerr** [comment]
> I think this should be one hyperlink, not sure if this is not easily doable.
Our LSP4XML definition supports
https://microsoft.github.io/language-server-protocol/specification#locationlink which should fix that. But it seems vscode doesn't support it now and supports only https://microsoft.github.io/language-server-protocol/specification#location

After debugging, it seems vscode doesn't support the capability `clientCapabilities.textDocument.definition.linkSupport` (see https://microsoft.github.io/language-server-protocol/specification#textDocument_definition). Once vscode will support it this problem should be gone.

**Comment by angelozerr** [comment]
@NikolasKomonen do you think we can merge it this PR? @fbricon what do you think?

**Comment by NikolasKomonen** [comment]
@fbricon It works great for me, I think it can be merged.

**Comment by angelozerr** [comment]
Thanks @NikolasKomonen for your review!

**Pull request merged**
