### PR TITLE
Add support for `textDocument/completion` for types definition in XML Schema

### LINKED ISSUE #451: Add support for `textDocument/completion` for xs:element/@name / xs:extension/@base
Add support for `textDocument/completion` for xs:element/@name / xs:extension/@base

With the XML sample:

```xml
<?xml version="1.1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	
	<xs:element name="employee" type="fullpersoninfo">
		
	</xs:element>
	
	<xs:complexType name="personinfo">
		<xs:sequence> 
			<xs:element name="firstname" type="xs:string" />
			<xs:element name="lastname" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="fullpersoninfo">
		<xs:complexContent>
			<xs:extension base="personinfo">
				<xs:sequence>
					<xs:element name="address" type="xs:string" />
					<xs:element name="city" type="xs:string" />
					<xs:element name="country" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
</xs:schema>
```

Completion on `<xs:element name="employee" type="|` and  `<xs:extension base="|` should display 
 * `fullpersoninfo` 
 * `personinfo`
 * `xs:string`, `xs:number`, etc

### PR DESCRIPTION
**Pull request by angelozerr**
Fix #451

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
To test this PR I suggest to tes it with:

 - https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/resources/schemas/xsd/XMLSchema.xsd and 
 - https://maven.apache.org/xsd/maven-4.0.0.xsd

Completion are triggered from 

 - `type` attribute (ex : xs:element type=). This attribute reference complex and simple type
 - `base` attribute (ex : xs:extension base=) This attribute reference complex type if parent is complexType or complexContent and simple type if parent is simpleType or simpleContent
 - `ref attribute (ex : xs:element ref= ) This attribute reference an xs:element (and xs:group reference a xs:group)

**Comment by NikolasKomonen** [comment]
Not sure if it is this PR. But when I do completion for the attribute `type`

```xml
<xs:element ... ty|>
```

The cursor should appear inside the quotations:

```xml
<xs:element ... type="|">
```

Right now the cursor is after the quotes:

```xml
```xml
<xs:element ... type=""|>
```
```

**Comment by angelozerr** [comment]
@NikolasKomonen this behaviour already existed. The generated attribute in this case is `type="$1"$0` where `$0` is the cursor.  The basic idea is to set the cursor after quote to fill another attributes. See https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/extensions/contentmodel/utils/XMLGenerator.java#L211

If you don't like this behaviour, please create a new issue for that and we will discuss about it.

**Comment by angelozerr** [comment]
Thanks Nick for tout review. @xorye please vive me feedback too if you have time to play with this pr

**Comment by angelozerr** [comment]
Thanks @NikolasKomonen  for your review

**Pull request merged**
