### PR TITLE
Leverage Maven's dependency management mechanism

### PR DESCRIPTION
**Pull request by fbricon**
... to centralize all common dependency versions in the parent project

### CODE REVIEW

**Comment by fbricon** [comment]
Also need to prune unused dependencies. mvn dependency:ananlyze yields:

```
org.eclipse.lsp4xml:
[WARNING] Used undeclared dependencies found:
[WARNING]    xml-apis:xml-apis:jar:1.4.01:compile
[WARNING] Unused declared dependencies found:
[WARNING]    org.eclipse.xtext:org.eclipse.xtext.xbase.lib:jar:2.14.0:compile
[WARNING]    xml-resolver:xml-resolver:jar:1.2:compile

org.eclipse.lsp4xml.emmet:
[WARNING] Unused declared dependencies found:
[WARNING]    com.google.code.gson:gson:jar:2.7:compile
[WARNING]    org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:jar:0.5.0.M1:compile
[WARNING]    org.eclipse.xtext:org.eclipse.xtext.xbase.lib:jar:2.14.0:compile

org.eclipse.lsp4xml.xsl:
[WARNING] Unused declared dependencies found:
[WARNING]    com.google.code.gson:gson:jar:2.7:compile
[WARNING]    org.eclipse.lsp4j:org.eclipse.lsp4j:jar:0.5.0.M1:compile
[WARNING]    org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:jar:0.5.0.M1:compile
[WARNING]    org.eclipse.xtext:org.eclipse.xtext.xbase.lib:jar:2.14.0:compile
[WARNING]    junit:junit:jar:4.12:test
```

**Comment by angelozerr** [comment]
Good catch! Please remove unused dependencies.

**Comment by fbricon** [comment]
removed unused deps

**Comment by fbricon** [comment]
The Travis build keeps referencing the snapshot repositories, which makes no sense. Build works for me locally. 
I've modified the travis.yml file but to tune the cached repo, but travis seems to ignore it for pull-requests.
@angelozerr please try it locally and if it works merge the PR. If the build still fails on travis on master after that, we can still revert.

**Comment by apupier** [comment]
Travis caches can be cleared https://docs.travis-ci.com/user/caching/#clearing-caches

**Pull request merged**
