### PR TITLE
Issue #288 - Generate OSGi and p2 data

### PR DESCRIPTION
**Pull request by mickaelistria**
Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
This coupled with https://www.jfrog.com/confluence/display/RTF/P2+Repositories should make the LS available as a p2 artifact.

**Comment by fbricon** [comment]
tycho-eclipserun-plugin is drunk. Build fails using both jdk 1.8 or 11.02 with the same error:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for lsp4xml 0.4.0-SNAPSHOT:
[INFO]
[INFO] lsp4xml ............................................ SUCCESS [  0.137 s]
[INFO] org.eclipse.lsp4xml ................................ FAILURE [  7.065 s]
[INFO] lsp4xml-extensions ................................. SKIPPED
[INFO] org.eclipse.lsp4xml.extensions.emmet ............... SKIPPED
[INFO] org.eclipse.lsp4xml.extensions.web ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.307 s
[INFO] Finished at: 2019-02-18T10:58:29-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-eclipserun-plugin:1.3.0:eclipse-run (generate-p2-site) on project org.eclipse.lsp4xml: Error while executing platform: Non-existing JDK home configuration at /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.eclipse.lsp4xml
➜  lsp4xml git:(288-osgi-p2) ll /Library/Java/JavaVirtualMachines/
total 0
drwxr-xr-x  3 root  wheel    96B 23 Aug 16:15 jdk-10.0.2.jdk
drwxr-xr-x  3 root  wheel    96B 26 May  2018 jdk-11.jdk
drwxr-xr-x  3 root  wheel    96B 24 Jan  2018 jdk-9.0.4.jdk
drwxr-xr-x  3 root  wheel    96B 13 Apr  2018 jdk1.7.0_80.jdk
drwxr-xr-x  3 root  wheel    96B 24 Jan  2018 jdk1.8.0_161.jdk
drwxr-xr-x  3 root  wheel    96B 27 Jul  2018 jdk1.8.0_181.jdk
```

The p2 processing will likely increase the build time significantly, I'd rather have it moved to a Maven profile I can disable easily.

**Comment by fbricon** [comment]
So the missing jdk, was caused by a stale toolchain.xml file, I fixed it.
So I can confirm the build is now 3 times slower when no executing the tests (eg. when rebuilding in the context of vscode-xml). Definitely want to be able to skip the unnecessary p2 processing for a quicker turnaround.

**Comment by mickaelistria** [comment]
Ok, I'll try to put all that in a profile.

**Comment by mickaelistria** [comment]
PR updated. p2 metadata generation is now in a `generate-p2` profile.

**Comment by mickaelistria** [comment]
Thanks!

**Pull request merged**
