### PR TITLE
Considers restructure of initOption settings JSON

### PR DESCRIPTION
**Pull request by NikolasKomonen**

### CODE REVIEW

**Comment by angelozerr** [comment]
@NikolasKomonen I'm already working on this issue, please provide a PR with your format tests in order toI don't break something. Thanks!

**Comment by angelozerr** [comment]
@NikolasKomonen I reject your PR, because I have managed your case with an another mean (using Pojo, instead of navigations to JSonObject). See my big commit at https://github.com/angelozerr/lsp4xml/commit/f8416c86613977cc04476c430481ac3a2258ddc9

I have updated your code with formatting options.  I have too written test about settings at https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/test/java/org/eclipse/lsp4xml/settings/SettingsTest.java

Hope you will like it.

**Comment by fbricon** [comment]
@angelozerr Currently, initialization options == settings, which might not be true in the future. The intent of that PR is to make sure the settings are passed to initialization options via a `settings` key, so that  initialization options  can contain other parameters. This is not covered by your latest commit. So we need a new PR.

**Comment by angelozerr** [comment]
@fbricon are you sure? Here the InitializeParams request that I receive with Eclipse IDE (settings = initializationOptions/settings)

```json
{
  "jsonrpc": "2.0",
  "id": "1",
  "method": "initialize",
  "params": {
    "processId": 12524,
    "rootPath": ".../test/",
    "rootUri": ".../test/",
    "initializationOptions": {
      "settings": {
        "fileAssociations": [
          {
            "systemId": src\\test\\resources\\xsd\\spring-beans-3.0.xsd",
            "pattern": "**/test*.xml"
          },
          {
            "systemId": "src\\test\\resources\\xsd\\projectDescription.xsd",
            "pattern": "projectDescription.xml"
          }
        ],
        "catalogs": [
          "src\\test\\resources\\catalogs\\catalog.xml"
        ],
        "format": {
          "tabSize": 10,
          "insertSpaces": false,
          "splitAttributes": true,
          "joinCDATALines": true,
          "formatComments": true,
          "joinCommentLines": true
        }
      }
    },
    "capabilities": {
      "workspace": {
        "applyEdit": true,
        "symbol": {},
        "executeCommand": {
          "dynamicRegistration": true
        },
        "workspaceFolders": true
      },
      "textDocument": {
        "synchronization": {
          "willSave": true,
          "willSaveWaitUntil": true,
          "didSave": true
        },
        "completion": {
          "completionItem": {
            "snippetSupport": true
          }
        },
        "hover": {},
        "signatureHelp": {},
        "references": {},
        "documentHighlight": {},
        "documentSymbol": {},
        "formatting": {},
        "rangeFormatting": {},
        "definition": {},
        "codeAction": {
          "codeActionLiteralSupport": {}
        },
        "codeLens": {},
        "documentLink": {},
        "colorProvider": {},
        "rename": {}
      }
    },
    "clientName": "Eclipse IDE",
    "trace": "off"
  }
}
```

**Comment by fbricon** [comment]
@angelozerr my bad, it works as expected. We cool

**Comment by angelozerr** [comment]
> @angelozerr my bad, it works as expected. We cool

Great!

**Pull request closed without merging**
