### PR TITLE
Add support for `textDocument/references` for DTD

### LINKED ISSUE #234: Add support for `textDocument/references` for DTD
Support for references between DTD elements.

```
<!ELEMENT TVSCHEDULE (CHANNEL>
<!ELEMENT CHANNEL  <-- Find references shows <!ELEMENT TVSCHEDULE


```

See the demo:

DTDReferences

### PR DESCRIPTION
**Pull request by angelozerr**
Fixes #234

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by NikolasKomonen** [comment]
@angelozerr If I try to peek a reference of a value that is not the definition I don't get any references.

eg:

```xml
<!ELEMENT font-fa|ce (X) > <-- peek references here gives the ATTLIST font-face reference
<!ATTLIST font-fa|ce >  <-- peek references here gives no references
```

Not sure if that is a design choice.

Otherwise, everything else works great.

**Comment by angelozerr** [comment]
`<!ATTLIST font-face` is linked to `<!ELEMENT font-face` (you can check that with definition on ATTLIST font-face. So if you find references from `<!ELEMENT font-face` you should see linked `<!ATTLIST font-face`.

**Comment by NikolasKomonen** [comment]
@angelozerr I understand that, but if I do peek definition on `<!ATTLIST font-face>` no options appear.

**Comment by angelozerr** [comment]
You should. If I test with svg.dtd, definition from <!ATTLIST font-face to <!ELEMENT font-face is working?

**Comment by angelozerr** [comment]
Thanks @NikolasKomonen for your review, please create an issue with missing feature.

**Pull request merged**
